name: Create Release sing-box Mediatek MT7622

# Триггеры запуска:
on:
  # 1. При создании тега в репозитории (например, v1.0.0)
  push:
    tags:
      - "v*.*.*"
  # 2. Для ручного запуска (кнопка "Run workflow" в GitHub Actions)
  workflow_dispatch:

jobs:
  build:
    # Имя сборки
    name: "v${{ matrix.tag }} - ${{ matrix.build_env.pkgarch}} :: ${{ matrix.build_env.target}}/${{ matrix.build_env.subtarget}} build"
    # Cреда сборки
    runs-on: ubuntu-latest
    
    # Матрица сборки, использующая ваши точные параметры
    strategy:
      matrix:
        tag: ['24.10.3'] 
        build_env:
          - pkgarch: aarch64_cortex-a53
            target: mediatek
            subtarget: mt7622 

    steps:
      # 1. Получаем исходники ImmortalWRT нужной версии
      - name: Checkout исходников ImmortalWRT
        uses: actions/checkout@v4
        with:
          repository: immortalwrt/immortalwrt
          ref: v${{ matrix.tag }} 
          fetch-depth: 0 # Нужен полный клон для работы с тегами

      # 2. Настраиваем фиды и конфигурацию сборки
      - name: Update and install feeds
        run: |
          pkgarch=${{ matrix.build_env.pkgarch}}
          target=${{ matrix.build_env.target}}
          subtarget=${{ matrix.build_env.subtarget}}
          echo "Building for: v${{ matrix.tag }}, Target: ${target}, Subtarget: ${subtarget}, Arch: ${pkgarch}"
          
          # Скачиваем официальный feeds.buildinfo для вашего релиза
          wget https://downloads.immortalwrt.org/releases/${{ matrix.tag }}/targets/${target}/${subtarget}/feeds.buildinfo -O feeds.conf
          
          # Добавляем фид shtorm-7
          echo "src-git shtorm7 https://github.com/shtorm-7/sing-box-extended.git;main" >> ./feeds.conf
          
          # Обновляем и устанавливаем все фиды
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          # Скачиваем официальный config.buildinfo для вашего релиза
          wget https://downloads.immortalwrt.org/releases/${{ matrix.tag }}/targets/${target}/${subtarget}/config.buildinfo -O .config
          make defconfig

      # 3. Собираем тулчейн (компиляторы) и ядро
      - name: Make Download and World (Toolchain)
        run: |
          export FORCE_UNSAFE_CONFIGURE=1
          
          # Добавляем нужные пакеты в .config
          echo "CONFIG_PACKAGE_sing-box=m" >> .config
          echo "CONFIG_PACKAGE_luci-app-sing-box=m" >> .config
          
          # Добавляем настройки для компиляции Go (нужны для sing-box)
          if [[ $(uname -m) == "aarch64" ]]; then
            echo 'CONFIG_GOLANG_EXTERNAL_BOOTSTRAP_ROOT="/usr/local/go/bin/go"' >> .config
            echo 'CONFIG_GOLANG_BUILD_CACHE_DIR=""' >> .config
          fi
          
          make defconfig
          
          # Собираем тулчейн и ядро
          echo "Make tools/install"
          make tools/install -i -j $(nproc)
          echo "Make toolchain/install"
          make toolchain/install -i -j $(nproc)
          echo "Make Kernel Compile"
          make target/linux/compile -i -j $(nproc)

      # 4. Собираем только нужные нам .ipk пакеты
      - name: Make ipks for sing-box
        run: |
          # Путь к Makefile пакета в фиде
          make -j $(nproc) package/feeds/shtorm7/sing-box/{clean,download,prepare,compile}
          make -j $(nproc) package/feeds/shtorm7/luci-app-sing-box/{clean,download,prepare,compile}

      # 5. Готовим артефакты (переименовываем .ipk)
      - name: Prepare artifacts
        run: |
          tag_name=${{ github.ref_name }}
          # Задаем имя по умолчанию, если запуск был вручную
          if [ -z "$tag_name" ]; then
            tag_name="manual-build"
          fi
          
          mkdir -p singboxrelease
          # Формируем красивое имя файла
          postfix="${tag_name}_v${{ matrix.tag }}_${{ matrix.build_env.pkgarch}}_${{ matrix.build_env.target}}_${{ matrix.build_env.subtarget}}"
          
          # Копируем и переименовываем .ipk
          cp bin/packages/${{ matrix.build_env.pkgarch }}/shtorm7/sing-box_*.ipk singboxrelease/sing-box_${postfix}.ipk
          cp bin/packages/${{ matrix.build_env.pkgarch }}/shtorm7/luci-app-sing-box_*.ipk singboxrelease/luci-app-sing-box_${postfix}.ipk

      # 6. Публикуем Релиз (только если запуск был по тегу)
      - name: Release (publish to GitHub Releases)
        uses: softprops/action-gh-release@v1
        with:
          files: singboxrelease/*.ipk
        # Условие: выполнять только при запуске через push тега
        if: startsWith(github.ref, 'refs/tags/')

      # 7. Загружаем Артефакт (только если запуск был ручной)
      - name: Upload Artifact (for manual runs)
        uses: actions/upload-artifact@v4
        with:
          name: sing-box-packages
          path: singboxrelease/
        # Условие: выполнять только при запуске НЕ по тегу
        if: "!startsWith(github.ref, 'refs/tags/')"